/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    admins: Admin;
    'user-events': UserEvent;
    'emergency-contacts': EmergencyContact;
    addresses: Address;
    media: Media;
    posts: Post;
    vendors: Vendor;
    merchants: Merchant;
    'product-categories': ProductCategory;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    'user-events': UserEventsSelect<false> | UserEventsSelect<true>;
    'emergency-contacts': EmergencyContactsSelect<false> | EmergencyContactsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    merchants: MerchantsSelect<false> | MerchantsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Middle name (optional)
   */
  middleName?: string | null;
  /**
   * Name extension (e.g., Jr., Sr., III)
   */
  nameExtension?: string | null;
  /**
   * Unique username for login
   */
  username?: string | null;
  /**
   * Gender identity
   */
  gender?: ('male' | 'female' | 'other' | 'prefer_not_to_say') | null;
  /**
   * Civil status
   */
  civilStatus?: ('single' | 'married' | 'divorced' | 'widowed' | 'separated') | null;
  /**
   * Nationality
   */
  nationality?: string | null;
  /**
   * Date of birth
   */
  birthDate?: string | null;
  /**
   * Place of birth
   */
  placeOfBirth?: string | null;
  /**
   * Complete address
   */
  completeAddress?: string | null;
  /**
   * User role determines access permissions. Service accounts are for API key authentication.
   */
  role: 'admin' | 'customer' | 'service' | 'vendor';
  /**
   * Inactive users cannot log in
   */
  isActive?: boolean | null;
  /**
   * Last login timestamp
   */
  lastLogin?: string | null;
  /**
   * User profile picture
   */
  profilePicture?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  cloudinaryPublicId?: string | null;
  cloudinaryURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  /**
   * Link to user account
   */
  user: number | User;
  /**
   * Student Registration Number (unique identifier)
   */
  srn: string;
  /**
   * Marketing coupon code used during registration
   */
  couponCode?: string | null;
  /**
   * Date when customer enrolled in the program
   */
  enrollmentDate?: string | null;
  /**
   * Current learning level
   */
  currentLevel?: ('beginner' | 'intermediate' | 'advanced') | null;
  /**
   * Currently selected active address for this customer (for food delivery)
   */
  activeAddress?: (number | null) | Address;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage user addresses with Google Maps integration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  /**
   * User who owns this address
   */
  user: number | User;
  /**
   * Complete Google-formatted address (unedited from Google Maps)
   */
  formatted_address: string;
  /**
   * Google Place ID for reference and validation
   */
  google_place_id?: string | null;
  /**
   * Street number (from address_components: street_number)
   */
  street_number?: string | null;
  /**
   * Street name (from address_components: route)
   */
  route?: string | null;
  /**
   * Unit/apartment number (from address_components: subpremise)
   */
  subpremise?: string | null;
  /**
   * Barangay (from address_components: sublocality_level_1)
   */
  barangay?: string | null;
  /**
   * City/municipality (from address_components: locality)
   */
  locality?: string | null;
  /**
   * Province subdivision (from address_components: administrative_area_level_2)
   */
  administrative_area_level_2?: string | null;
  /**
   * Province/state (from address_components: administrative_area_level_1)
   */
  administrative_area_level_1?: string | null;
  /**
   * Country (from address_components: country)
   */
  country?: string | null;
  /**
   * ZIP/postal code (from address_components: postal_code)
   */
  postal_code?: string | null;
  /**
   * Latitude coordinate (from geometry.location.lat)
   */
  latitude?: number | null;
  /**
   * Longitude coordinate (from geometry.location.lng)
   */
  longitude?: number | null;
  /**
   * PostGIS GEOMETRY(POINT, 4326) for spatial queries - stored as GeoJSON
   */
  coordinates?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Elevation data in meters (optional)
   */
  altitude?: number | null;
  /**
   * Geocoding confidence score (1-100)
   */
  address_quality_score?: number | null;
  /**
   * Google Maps geocoding accuracy level
   */
  geocoding_accuracy?: ('ROOFTOP' | 'RANGE_INTERPOLATED' | 'GEOMETRIC_CENTER' | 'APPROXIMATE') | null;
  /**
   * Source of coordinate data
   */
  coordinate_source?: ('GPS' | 'GOOGLE_GEOCODING' | 'MANUAL' | 'ESTIMATED') | null;
  /**
   * Timestamp of last geocoding update
   */
  last_geocoded_at?: string | null;
  /**
   * Method used to verify address accuracy
   */
  verification_method?: ('GPS_CONFIRMED' | 'DELIVERY_CONFIRMED' | 'USER_CONFIRMED' | 'UNVERIFIED') | null;
  /**
   * PostGIS POLYGON for property boundaries - stored as GeoJSON
   */
  address_boundary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Default delivery radius in meters
   */
  service_radius_meters?: number | null;
  /**
   * Delivery instructions and accessibility information
   */
  accessibility_notes?: string | null;
  /**
   * Nearby landmarks for easier location identification
   */
  landmark_description?: string | null;
  /**
   * Type of address for categorization
   */
  address_type: 'home' | 'work' | 'billing' | 'shipping' | 'pickup' | 'delivery';
  /**
   * Mark as default address for this user
   */
  is_default?: boolean | null;
  /**
   * Address has been verified through Google Maps
   */
  is_verified?: boolean | null;
  /**
   * Additional notes or delivery instructions
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  /**
   * Link to user account
   */
  user: number | User;
  /**
   * Administrative access level
   */
  adminLevel: 'system' | 'department' | 'content';
  /**
   * System-level permissions and capabilities
   */
  systemPermissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-events".
 */
export interface UserEvent {
  id: number;
  /**
   * User this event relates to
   */
  user: number | User;
  /**
   * Type of event that occurred
   */
  eventType:
    | 'USER_CREATED'
    | 'ROLE_CHANGED'
    | 'PROFILE_UPDATED'
    | 'USER_DEACTIVATED'
    | 'USER_REACTIVATED'
    | 'LOGIN_SUCCESS'
    | 'LOGIN_FAILED'
    | 'PASSWORD_CHANGED';
  /**
   * Event-specific data and context
   */
  eventData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * User who triggered this event (if applicable)
   */
  triggeredBy?: (number | null) | User;
  /**
   * When this event occurred
   */
  timestamp?: string | null;
  /**
   * IP address where event originated
   */
  ipAddress?: string | null;
  /**
   * User agent string from the request
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-contacts".
 */
export interface EmergencyContact {
  id: number;
  /**
   * User this emergency contact belongs to
   */
  user: number | User;
  /**
   * Emergency contact first name
   */
  firstName: string;
  /**
   * Emergency contact middle name (optional)
   */
  middleName?: string | null;
  /**
   * Emergency contact last name
   */
  lastName: string;
  /**
   * Emergency contact phone number
   */
  contactNumber: string;
  /**
   * Relationship to the user
   */
  relationship: 'parent' | 'spouse' | 'sibling' | 'child' | 'guardian' | 'friend' | 'relative' | 'other';
  /**
   * Emergency contact complete address
   */
  completeAddress: string;
  /**
   * Mark as primary emergency contact
   */
  isPrimary?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The main title/heading for this content
   */
  title: string;
  /**
   * URL-friendly version of the title (used in web addresses)
   */
  slug: string;
  /**
   * Main content body with rich text formatting
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Brief description for previews and SEO (recommended 150-160 characters)
   */
  excerpt?: string | null;
  /**
   * Main image displayed with this content
   */
  featuredImage?: (number | null) | Media;
  /**
   * Keywords and categories for organizing content
   */
  tags?:
    | {
        /**
         * Tag name (e.g., "web development", "tutorial")
         */
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Publication status - only published content is visible to the public
   */
  status: 'draft' | 'published';
  /**
   * When this content was/will be published
   */
  publishedAt?: string | null;
  /**
   * The user who created this content
   */
  author: number | User;
  /**
   * Search engine optimization settings (all optional)
   */
  seo?: {
    /**
     * SEO title for search engines (leave empty to use main title) - Max 60 characters recommended
     */
    title?: string | null;
    /**
     * SEO description for search engines (leave empty to use excerpt) - Max 160 characters recommended
     */
    description?: string | null;
    /**
     * Primary keyword you want this content to rank for
     */
    focusKeyword?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage business entities and vendor organizations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  /**
   * User account associated with this vendor (required)
   */
  user: number | User;
  /**
   * Business name (e.g., "Jollibee Corporation", "McDonald's Philippines")
   */
  businessName: string;
  /**
   * Legal business name as registered with government
   */
  legalName: string;
  /**
   * Government business registration number (DTI/SEC)
   */
  businessRegistrationNumber: string;
  /**
   * Tax Identification Number (TIN)
   */
  taxIdentificationNumber?: string | null;
  /**
   * Primary business contact email
   */
  primaryContactEmail: string;
  /**
   * Primary business contact phone number
   */
  primaryContactPhone: string;
  /**
   * Official business website URL
   */
  websiteUrl?: string | null;
  /**
   * Type of business operation
   */
  businessType:
    | 'restaurant'
    | 'fast_food'
    | 'grocery'
    | 'pharmacy'
    | 'convenience'
    | 'bakery'
    | 'coffee_shop'
    | 'other';
  /**
   * Types of cuisine offered (JSON array of strings)
   */
  cuisineTypes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Whether the vendor is currently active
   */
  isActive?: boolean | null;
  /**
   * Business verification status
   */
  verificationStatus: 'pending' | 'verified' | 'rejected' | 'suspended';
  /**
   * Date when vendor was onboarded to the platform
   */
  onboardingDate?: string | null;
  /**
   * Average rating across all merchant locations
   */
  averageRating?: number | null;
  /**
   * Total number of reviews across all locations
   */
  totalReviews?: number | null;
  /**
   * Total orders processed across all locations
   */
  totalOrders?: number | null;
  /**
   * Number of merchant locations under this vendor
   */
  totalMerchants?: number | null;
  /**
   * Business license document
   */
  businessLicense?: (number | null) | Media;
  /**
   * Tax certificate document
   */
  taxCertificate?: (number | null) | Media;
  /**
   * Business logo
   */
  logo?: (number | null) | Media;
  /**
   * Bank account holder name
   */
  bankAccountName?: string | null;
  /**
   * Bank account number for payments
   */
  bankAccountNumber?: string | null;
  /**
   * Bank name
   */
  bankName?: string | null;
  /**
   * Business description and overview
   */
  description?: string | null;
  /**
   * Default operating hours (can be overridden by individual merchants)
   */
  operatingHours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Social media and web presence
   */
  socialMediaLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    website?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage individual merchant locations and outlets
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchants".
 */
export interface Merchant {
  id: number;
  /**
   * Parent vendor/business entity
   */
  vendor: number | Vendor;
  /**
   * Specific outlet name (e.g., "Jollibee Manila", "McDonald's Quezon City")
   */
  outletName: string;
  /**
   * Internal reference code for the outlet (e.g., JB-MNL-001)
   */
  outletCode: string;
  /**
   * Contact information for this specific outlet
   */
  contactInfo?: {
    /**
     * Outlet contact phone number
     */
    phone?: string | null;
    /**
     * Outlet contact email
     */
    email?: string | null;
    /**
     * Store manager name
     */
    managerName?: string | null;
    /**
     * Store manager contact number
     */
    managerPhone?: string | null;
  };
  /**
   * Whether the merchant is currently active
   */
  isActive?: boolean | null;
  /**
   * Whether the merchant is currently accepting new orders
   */
  isAcceptingOrders?: boolean | null;
  /**
   * Current operational status
   */
  operationalStatus?: ('open' | 'closed' | 'busy' | 'temp_closed' | 'maintenance') | null;
  /**
   * Weekly operating schedule (JSON format)
   */
  operatingHours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Special operating hours for holidays or events (JSON array of objects with date, openTime, closeTime, isClosed, reason)
   */
  specialHours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Delivery policies and settings
   */
  deliverySettings?: {
    /**
     * Minimum order amount (PHP)
     */
    minimumOrderAmount?: number | null;
    /**
     * Base delivery fee (PHP)
     */
    deliveryFee?: number | null;
    /**
     * Order amount for free delivery (PHP)
     */
    freeDeliveryThreshold?: number | null;
    /**
     * Estimated delivery time in minutes
     */
    estimatedDeliveryTimeMinutes?: number | null;
    /**
     * Maximum delivery time promise
     */
    maxDeliveryTimeMinutes?: number | null;
  };
  /**
   * Visual content for the merchant
   */
  media?: {
    /**
     * Merchant thumbnail image (original size from Cloudinary)
     */
    thumbnail?: (number | null) | Media;
    /**
     * Store front photo
     */
    storeFrontImage?: (number | null) | Media;
    /**
     * Interior photos of the outlet (JSON array of media IDs)
     */
    interiorImages?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Menu board or promotional images (JSON array of media IDs)
     */
    menuImages?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Outlet description and special features
   */
  description?: string | null;
  /**
   * Special delivery or pickup instructions
   */
  specialInstructions?: string | null;
  /**
   * Tags for search and categorization (JSON array of strings)
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Currently active address for this merchant outlet (business location) - only addresses owned by the vendor user
   */
  activeAddress?: (number | null) | Address;
  /**
   * Denormalized latitude from active address for performance
   */
  merchant_latitude?: number | null;
  /**
   * Denormalized longitude from active address for performance
   */
  merchant_longitude?: number | null;
  /**
   * Location accuracy radius in meters
   */
  location_accuracy_radius?: number | null;
  /**
   * Current delivery radius in meters
   */
  delivery_radius_meters?: number | null;
  /**
   * Maximum possible delivery radius in meters
   */
  max_delivery_radius_meters?: number | null;
  /**
   * Minimum order amount for delivery (PHP)
   */
  min_order_amount?: number | null;
  /**
   * Base delivery fee (PHP)
   */
  delivery_fee_base?: number | null;
  /**
   * Per-kilometer delivery fee (PHP)
   */
  delivery_fee_per_km?: number | null;
  /**
   * Order amount for free delivery (PHP)
   */
  free_delivery_threshold?: number | null;
  /**
   * GeoJSON Point format for spatial queries - auto-populated from lat/lng
   */
  merchant_coordinates?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * PostGIS GEOMETRY(POLYGON, 4326) for delivery coverage area - for spatial queries
   */
  service_area_geometry?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * PostGIS GEOMETRY(MULTIPOLYGON, 4326) for premium delivery areas - for spatial queries
   */
  priority_zones_geometry?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * PostGIS GEOMETRY(MULTIPOLYGON, 4326) for no-delivery zones - for spatial queries
   */
  restricted_areas_geometry?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * PostGIS GEOMETRY(MULTIPOLYGON, 4326) for zone-specific delivery areas - for spatial queries
   */
  delivery_zones_geometry?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * PostGIS POLYGON for delivery coverage area - stored as GeoJSON (editable)
   */
  service_area?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * PostGIS MULTIPOLYGON for premium delivery areas - stored as GeoJSON (editable)
   */
  priority_zones?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * PostGIS MULTIPOLYGON for no-delivery zones - stored as GeoJSON (editable)
   */
  restricted_areas?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Zone-specific pricing configuration (JSONB format)
   */
  delivery_zones?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Average delivery time in minutes
   */
  avg_delivery_time_minutes?: number | null;
  /**
   * Delivery success rate (0.0 to 1.0)
   */
  delivery_success_rate?: number | null;
  /**
   * Surge pricing multiplier during peak hours
   */
  peak_hours_multiplier?: number | null;
  /**
   * Delivery-specific operating hours (JSONB format)
   */
  delivery_hours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Real-time delivery availability status
   */
  is_currently_delivering?: boolean | null;
  /**
   * Next available delivery time slot
   */
  next_available_slot?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Organize products into hierarchical categories for easy browsing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  /**
   * Category name (e.g., "Main Dishes", "Beverages", "Desserts")
   */
  name: string;
  /**
   * URL-friendly version of the name (auto-generated if empty)
   */
  slug: string;
  /**
   * Category description for customers
   */
  description?: string | null;
  /**
   * Parent category (leave empty for top-level categories)
   */
  parentCategory?: (number | null) | ProductCategory;
  /**
   * Hierarchy level (1 = top level, 2 = subcategory, etc.)
   */
  categoryLevel?: number | null;
  /**
   * Materialized path for efficient queries (auto-generated)
   */
  categoryPath?: string | null;
  /**
   * Order for displaying categories (lower numbers appear first)
   */
  displayOrder?: number | null;
  /**
   * Whether the category is currently active
   */
  isActive?: boolean | null;
  /**
   * Whether to feature this category prominently
   */
  isFeatured?: boolean | null;
  /**
   * Visual elements for the category
   */
  media?: {
    /**
     * Category icon (SVG preferred)
     */
    icon?: (number | null) | Media;
    /**
     * Banner image for category pages
     */
    bannerImage?: (number | null) | Media;
    /**
     * Thumbnail for category listings
     */
    thumbnailImage?: (number | null) | Media;
  };
  /**
   * Visual styling options
   */
  styling?: {
    /**
     * Hex color code for category theme (e.g., #FF6B35)
     */
    colorTheme?: string | null;
    /**
     * Background color for category cards
     */
    backgroundColor?: string | null;
    /**
     * Text color for category elements
     */
    textColor?: string | null;
    /**
     * Colors for gradient backgrounds (JSON array of hex color strings)
     */
    gradientColors?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Category-specific attributes and restrictions
   */
  attributes?: {
    /**
     * Type of products in this category
     */
    categoryType?:
      | (
          | 'food'
          | 'beverages'
          | 'desserts'
          | 'snacks'
          | 'groceries'
          | 'pharmacy'
          | 'personal_care'
          | 'household'
          | 'other'
        )
      | null;
    /**
     * Dietary attributes commonly found in this category (JSON array of strings)
     */
    dietaryTags?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Age restriction for products in this category
     */
    ageRestriction?: ('none' | '18_plus' | '21_plus') | null;
    /**
     * Whether products in this category require prescription
     */
    requiresPrescription?: boolean | null;
  };
  /**
   * Business rules and handling requirements
   */
  businessRules?: {
    /**
     * Whether products in this category can be customized
     */
    allowsCustomization?: boolean | null;
    /**
     * Whether products need special delivery handling
     */
    requiresSpecialHandling?: boolean | null;
    /**
     * Whether products in this category have expiration dates
     */
    hasExpirationDates?: boolean | null;
    /**
     * Whether products need refrigerated delivery
     */
    requiresRefrigeration?: boolean | null;
    /**
     * Maximum delivery time for products in this category (hours)
     */
    maxDeliveryTimeHours?: number | null;
  };
  /**
   * SEO optimization settings
   */
  seo?: {
    /**
     * SEO meta title
     */
    metaTitle?: string | null;
    /**
     * SEO meta description
     */
    metaDescription?: string | null;
    /**
     * SEO keywords for this category (JSON array of strings)
     */
    keywords?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Canonical URL for SEO
     */
    canonicalUrl?: string | null;
  };
  /**
   * Analytics and performance metrics
   */
  metrics?: {
    /**
     * Total number of products in this category
     */
    totalProducts?: number | null;
    /**
     * Total orders from this category
     */
    totalOrders?: number | null;
    /**
     * Average rating of products in this category
     */
    averageRating?: number | null;
    /**
     * Calculated popularity score
     */
    popularityScore?: number | null;
    /**
     * Number of times this category was viewed
     */
    viewCount?: number | null;
  };
  /**
   * Promotional campaigns and discounts
   */
  promotions?: {
    /**
     * Whether this category is currently being promoted
     */
    isPromotional?: boolean | null;
    /**
     * Promotional text to display with the category
     */
    promotionalText?: string | null;
    /**
     * Category-wide discount percentage
     */
    discountPercentage?: number | null;
    /**
     * When the promotion starts
     */
    promotionStartDate?: string | null;
    /**
     * When the promotion ends
     */
    promotionEndDate?: string | null;
  };
  /**
   * Availability and restriction settings
   */
  availability?: {
    /**
     * Hours when this category is available (JSON format)
     */
    availableHours?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Seasonal availability settings (JSON array of season objects)
     */
    seasonalAvailability?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Regional availability restrictions (JSON array of region objects)
     */
    regionRestrictions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'user-events';
        value: number | UserEvent;
      } | null)
    | ({
        relationTo: 'emergency-contacts';
        value: number | EmergencyContact;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'merchants';
        value: number | Merchant;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  middleName?: T;
  nameExtension?: T;
  username?: T;
  gender?: T;
  civilStatus?: T;
  nationality?: T;
  birthDate?: T;
  placeOfBirth?: T;
  completeAddress?: T;
  role?: T;
  isActive?: T;
  lastLogin?: T;
  profilePicture?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  user?: T;
  srn?: T;
  couponCode?: T;
  enrollmentDate?: T;
  currentLevel?: T;
  activeAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  user?: T;
  adminLevel?: T;
  systemPermissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-events_select".
 */
export interface UserEventsSelect<T extends boolean = true> {
  user?: T;
  eventType?: T;
  eventData?: T;
  triggeredBy?: T;
  timestamp?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-contacts_select".
 */
export interface EmergencyContactsSelect<T extends boolean = true> {
  user?: T;
  firstName?: T;
  middleName?: T;
  lastName?: T;
  contactNumber?: T;
  relationship?: T;
  completeAddress?: T;
  isPrimary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  user?: T;
  formatted_address?: T;
  google_place_id?: T;
  street_number?: T;
  route?: T;
  subpremise?: T;
  barangay?: T;
  locality?: T;
  administrative_area_level_2?: T;
  administrative_area_level_1?: T;
  country?: T;
  postal_code?: T;
  latitude?: T;
  longitude?: T;
  coordinates?: T;
  altitude?: T;
  address_quality_score?: T;
  geocoding_accuracy?: T;
  coordinate_source?: T;
  last_geocoded_at?: T;
  verification_method?: T;
  address_boundary?: T;
  service_radius_meters?: T;
  accessibility_notes?: T;
  landmark_description?: T;
  address_type?: T;
  is_default?: T;
  is_verified?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinaryPublicId?: T;
  cloudinaryURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  author?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyword?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  user?: T;
  businessName?: T;
  legalName?: T;
  businessRegistrationNumber?: T;
  taxIdentificationNumber?: T;
  primaryContactEmail?: T;
  primaryContactPhone?: T;
  websiteUrl?: T;
  businessType?: T;
  cuisineTypes?: T;
  isActive?: T;
  verificationStatus?: T;
  onboardingDate?: T;
  averageRating?: T;
  totalReviews?: T;
  totalOrders?: T;
  totalMerchants?: T;
  businessLicense?: T;
  taxCertificate?: T;
  logo?: T;
  bankAccountName?: T;
  bankAccountNumber?: T;
  bankName?: T;
  description?: T;
  operatingHours?: T;
  socialMediaLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        website?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchants_select".
 */
export interface MerchantsSelect<T extends boolean = true> {
  vendor?: T;
  outletName?: T;
  outletCode?: T;
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        managerName?: T;
        managerPhone?: T;
      };
  isActive?: T;
  isAcceptingOrders?: T;
  operationalStatus?: T;
  operatingHours?: T;
  specialHours?: T;
  deliverySettings?:
    | T
    | {
        minimumOrderAmount?: T;
        deliveryFee?: T;
        freeDeliveryThreshold?: T;
        estimatedDeliveryTimeMinutes?: T;
        maxDeliveryTimeMinutes?: T;
      };
  media?:
    | T
    | {
        thumbnail?: T;
        storeFrontImage?: T;
        interiorImages?: T;
        menuImages?: T;
      };
  description?: T;
  specialInstructions?: T;
  tags?: T;
  activeAddress?: T;
  merchant_latitude?: T;
  merchant_longitude?: T;
  location_accuracy_radius?: T;
  delivery_radius_meters?: T;
  max_delivery_radius_meters?: T;
  min_order_amount?: T;
  delivery_fee_base?: T;
  delivery_fee_per_km?: T;
  free_delivery_threshold?: T;
  merchant_coordinates?: T;
  service_area_geometry?: T;
  priority_zones_geometry?: T;
  restricted_areas_geometry?: T;
  delivery_zones_geometry?: T;
  service_area?: T;
  priority_zones?: T;
  restricted_areas?: T;
  delivery_zones?: T;
  avg_delivery_time_minutes?: T;
  delivery_success_rate?: T;
  peak_hours_multiplier?: T;
  delivery_hours?: T;
  is_currently_delivering?: T;
  next_available_slot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parentCategory?: T;
  categoryLevel?: T;
  categoryPath?: T;
  displayOrder?: T;
  isActive?: T;
  isFeatured?: T;
  media?:
    | T
    | {
        icon?: T;
        bannerImage?: T;
        thumbnailImage?: T;
      };
  styling?:
    | T
    | {
        colorTheme?: T;
        backgroundColor?: T;
        textColor?: T;
        gradientColors?: T;
      };
  attributes?:
    | T
    | {
        categoryType?: T;
        dietaryTags?: T;
        ageRestriction?: T;
        requiresPrescription?: T;
      };
  businessRules?:
    | T
    | {
        allowsCustomization?: T;
        requiresSpecialHandling?: T;
        hasExpirationDates?: T;
        requiresRefrigeration?: T;
        maxDeliveryTimeHours?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
      };
  metrics?:
    | T
    | {
        totalProducts?: T;
        totalOrders?: T;
        averageRating?: T;
        popularityScore?: T;
        viewCount?: T;
      };
  promotions?:
    | T
    | {
        isPromotional?: T;
        promotionalText?: T;
        discountPercentage?: T;
        promotionStartDate?: T;
        promotionEndDate?: T;
      };
  availability?:
    | T
    | {
        availableHours?: T;
        seasonalAvailability?: T;
        regionRestrictions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}