/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    admins: Admin;
    'user-events': UserEvent;
    'emergency-contacts': EmergencyContact;
    addresses: Address;
    media: Media;
    posts: Post;
    vendors: Vendor;
    merchants: Merchant;
    'product-categories': ProductCategory;
    products: Product;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    'user-events': UserEventsSelect<false> | UserEventsSelect<true>;
    'emergency-contacts': EmergencyContactsSelect<false> | EmergencyContactsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    merchants: MerchantsSelect<false> | MerchantsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Middle name (optional)
   */
  middleName?: string | null;
  /**
   * Name extension (e.g., Jr., Sr., III)
   */
  nameExtension?: string | null;
  /**
   * Unique username for login
   */
  username?: string | null;
  /**
   * Gender identity
   */
  gender?: ('male' | 'female' | 'other' | 'prefer_not_to_say') | null;
  /**
   * Civil status
   */
  civilStatus?: ('single' | 'married' | 'divorced' | 'widowed' | 'separated') | null;
  /**
   * Nationality
   */
  nationality?: string | null;
  /**
   * Date of birth
   */
  birthDate?: string | null;
  /**
   * Place of birth
   */
  placeOfBirth?: string | null;
  /**
   * Complete address
   */
  completeAddress?: string | null;
  /**
   * User role determines access permissions. Service accounts are for API key authentication.
   */
  role: 'admin' | 'customer' | 'service' | 'vendor';
  /**
   * Inactive users cannot log in
   */
  isActive?: boolean | null;
  /**
   * Last login timestamp
   */
  lastLogin?: string | null;
  /**
   * User profile picture
   */
  profilePicture?: (number | null) | Media;
  /**
   * Currently selected active address for this user (for food delivery)
   */
  activeAddress?: (number | null) | Address;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  cloudinaryPublicId?: string | null;
  cloudinaryURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage user addresses with Google Maps integration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  /**
   * User who owns this address
   */
  user: number | User;
  /**
   * Complete Google-formatted address (unedited from Google Maps)
   */
  formatted_address: string;
  /**
   * Google Place ID for reference and validation
   */
  google_place_id?: string | null;
  /**
   * Street number (from address_components: street_number)
   */
  street_number?: string | null;
  /**
   * Street name (from address_components: route)
   */
  route?: string | null;
  /**
   * Unit/apartment number (from address_components: subpremise)
   */
  subpremise?: string | null;
  /**
   * Barangay (from address_components: sublocality_level_1)
   */
  barangay?: string | null;
  /**
   * City/municipality (from address_components: locality)
   */
  locality?: string | null;
  /**
   * Province subdivision (from address_components: administrative_area_level_2)
   */
  administrative_area_level_2?: string | null;
  /**
   * Province/state (from address_components: administrative_area_level_1)
   */
  administrative_area_level_1?: string | null;
  /**
   * Country (from address_components: country)
   */
  country?: string | null;
  /**
   * ZIP/postal code (from address_components: postal_code)
   */
  postal_code?: string | null;
  /**
   * Latitude coordinate (from geometry.location.lat)
   */
  latitude?: number | null;
  /**
   * Longitude coordinate (from geometry.location.lng)
   */
  longitude?: number | null;
  /**
   * Type of address for categorization
   */
  address_type: 'home' | 'work' | 'billing' | 'shipping' | 'pickup' | 'delivery';
  /**
   * Mark as default address for this user
   */
  is_default?: boolean | null;
  /**
   * Address has been verified through Google Maps
   */
  is_verified?: boolean | null;
  /**
   * Additional notes or delivery instructions
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  /**
   * Link to user account
   */
  user: number | User;
  /**
   * Student Registration Number (unique identifier)
   */
  srn: string;
  /**
   * Marketing coupon code used during registration
   */
  couponCode?: string | null;
  /**
   * Date when customer enrolled in the program
   */
  enrollmentDate?: string | null;
  /**
   * Current learning level
   */
  currentLevel?: ('beginner' | 'intermediate' | 'advanced') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  /**
   * Link to user account
   */
  user: number | User;
  /**
   * Administrative access level
   */
  adminLevel: 'system' | 'department' | 'content';
  /**
   * System-level permissions and capabilities
   */
  systemPermissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-events".
 */
export interface UserEvent {
  id: number;
  /**
   * User this event relates to
   */
  user: number | User;
  /**
   * Type of event that occurred
   */
  eventType:
    | 'USER_CREATED'
    | 'ROLE_CHANGED'
    | 'PROFILE_UPDATED'
    | 'USER_DEACTIVATED'
    | 'USER_REACTIVATED'
    | 'LOGIN_SUCCESS'
    | 'LOGIN_FAILED'
    | 'PASSWORD_CHANGED';
  /**
   * Event-specific data and context
   */
  eventData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * User who triggered this event (if applicable)
   */
  triggeredBy?: (number | null) | User;
  /**
   * When this event occurred
   */
  timestamp?: string | null;
  /**
   * IP address where event originated
   */
  ipAddress?: string | null;
  /**
   * User agent string from the request
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-contacts".
 */
export interface EmergencyContact {
  id: number;
  /**
   * User this emergency contact belongs to
   */
  user: number | User;
  /**
   * Emergency contact first name
   */
  firstName: string;
  /**
   * Emergency contact middle name (optional)
   */
  middleName?: string | null;
  /**
   * Emergency contact last name
   */
  lastName: string;
  /**
   * Emergency contact phone number
   */
  contactNumber: string;
  /**
   * Relationship to the user
   */
  relationship: 'parent' | 'spouse' | 'sibling' | 'child' | 'guardian' | 'friend' | 'relative' | 'other';
  /**
   * Emergency contact complete address
   */
  completeAddress: string;
  /**
   * Mark as primary emergency contact
   */
  isPrimary?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The main title/heading for this content
   */
  title: string;
  /**
   * URL-friendly version of the title (used in web addresses)
   */
  slug: string;
  /**
   * Main content body with rich text formatting
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Brief description for previews and SEO (recommended 150-160 characters)
   */
  excerpt?: string | null;
  /**
   * Main image displayed with this content
   */
  featuredImage?: (number | null) | Media;
  /**
   * Keywords and categories for organizing content
   */
  tags?:
    | {
        /**
         * Tag name (e.g., "web development", "tutorial")
         */
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Publication status - only published content is visible to the public
   */
  status: 'draft' | 'published';
  /**
   * When this content was/will be published
   */
  publishedAt?: string | null;
  /**
   * The user who created this content
   */
  author: number | User;
  /**
   * Search engine optimization settings (all optional)
   */
  seo?: {
    /**
     * SEO title for search engines (leave empty to use main title) - Max 60 characters recommended
     */
    title?: string | null;
    /**
     * SEO description for search engines (leave empty to use excerpt) - Max 160 characters recommended
     */
    description?: string | null;
    /**
     * Primary keyword you want this content to rank for
     */
    focusKeyword?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage business entities and vendor organizations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  /**
   * Business name (e.g., "Jollibee Corporation", "McDonald's Philippines")
   */
  businessName: string;
  /**
   * Legal business name as registered with government
   */
  legalName: string;
  /**
   * Government business registration number (DTI/SEC)
   */
  businessRegistrationNumber: string;
  /**
   * Tax Identification Number (TIN)
   */
  taxIdentificationNumber?: string | null;
  /**
   * Primary business contact email
   */
  primaryContactEmail: string;
  /**
   * Primary business contact phone number
   */
  primaryContactPhone: string;
  /**
   * Official business website URL
   */
  websiteUrl?: string | null;
  /**
   * Type of business operation
   */
  businessType:
    | 'restaurant'
    | 'fast_food'
    | 'grocery'
    | 'pharmacy'
    | 'convenience'
    | 'bakery'
    | 'coffee_shop'
    | 'other';
  /**
   * Types of cuisine offered (JSON array of strings)
   */
  cuisineTypes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Whether the vendor is currently active
   */
  isActive?: boolean | null;
  /**
   * Business verification status
   */
  verificationStatus: 'pending' | 'verified' | 'rejected' | 'suspended';
  /**
   * Date when vendor was onboarded to the platform
   */
  onboardingDate?: string | null;
  /**
   * Average rating across all merchant locations
   */
  averageRating?: number | null;
  /**
   * Total number of reviews across all locations
   */
  totalReviews?: number | null;
  /**
   * Total orders processed across all locations
   */
  totalOrders?: number | null;
  /**
   * Number of merchant locations under this vendor
   */
  totalMerchants?: number | null;
  /**
   * Business license document
   */
  businessLicense?: (number | null) | Media;
  /**
   * Tax certificate document
   */
  taxCertificate?: (number | null) | Media;
  /**
   * Business logo
   */
  logo?: (number | null) | Media;
  /**
   * Bank account holder name
   */
  bankAccountName?: string | null;
  /**
   * Bank account number for payments
   */
  bankAccountNumber?: string | null;
  /**
   * Bank name
   */
  bankName?: string | null;
  /**
   * Business description and overview
   */
  description?: string | null;
  /**
   * Default operating hours (can be overridden by individual merchants)
   */
  operatingHours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Social media and web presence
   */
  socialMediaLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    website?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage individual merchant locations and outlets
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchants".
 */
export interface Merchant {
  id: number;
  /**
   * Parent vendor/business entity
   */
  vendor: number | Vendor;
  /**
   * Specific outlet name (e.g., "Jollibee Manila", "McDonald's Quezon City")
   */
  outletName: string;
  /**
   * Internal reference code for the outlet (e.g., JB-MNL-001)
   */
  outletCode: string;
  /**
   * Complete address information
   */
  address: {
    /**
     * Complete street address
     */
    streetAddress: string;
    /**
     * Barangay
     */
    barangay?: string | null;
    /**
     * City
     */
    city: string;
    /**
     * Province/State
     */
    province: string;
    /**
     * Postal/ZIP code
     */
    postalCode?: string | null;
    /**
     * Country
     */
    country?: string | null;
  };
  /**
   * Geographic location and delivery coverage
   */
  location: {
    /**
     * Latitude coordinate for delivery radius calculations
     */
    latitude: number;
    /**
     * Longitude coordinate for delivery radius calculations
     */
    longitude: number;
    /**
     * Delivery radius in kilometers
     */
    deliveryRadiusKm?: number | null;
  };
  /**
   * Contact information for this specific outlet
   */
  contactInfo?: {
    /**
     * Outlet contact phone number
     */
    phone?: string | null;
    /**
     * Outlet contact email
     */
    email?: string | null;
    /**
     * Store manager name
     */
    managerName?: string | null;
    /**
     * Store manager contact number
     */
    managerPhone?: string | null;
  };
  /**
   * Whether the merchant is currently active
   */
  isActive?: boolean | null;
  /**
   * Whether the merchant is currently accepting new orders
   */
  isAcceptingOrders?: boolean | null;
  /**
   * Current operational status
   */
  operationalStatus?: ('open' | 'closed' | 'busy' | 'temp_closed' | 'maintenance') | null;
  /**
   * Weekly operating schedule (JSON format)
   */
  operatingHours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Special operating hours for holidays or events (JSON array of objects with date, openTime, closeTime, isClosed, reason)
   */
  specialHours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Delivery policies and settings
   */
  deliverySettings?: {
    /**
     * Minimum order amount (PHP)
     */
    minimumOrderAmount?: number | null;
    /**
     * Base delivery fee (PHP)
     */
    deliveryFee?: number | null;
    /**
     * Order amount for free delivery (PHP)
     */
    freeDeliveryThreshold?: number | null;
    /**
     * Estimated delivery time in minutes
     */
    estimatedDeliveryTimeMinutes?: number | null;
    /**
     * Maximum delivery time promise
     */
    maxDeliveryTimeMinutes?: number | null;
  };
  /**
   * Visual content for the merchant
   */
  media?: {
    /**
     * Merchant thumbnail image (original size from Cloudinary)
     */
    thumbnail?: (number | null) | Media;
    /**
     * Store front photo
     */
    storeFrontImage?: (number | null) | Media;
    /**
     * Interior photos of the outlet (JSON array of media IDs)
     */
    interiorImages?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Menu board or promotional images (JSON array of media IDs)
     */
    menuImages?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Outlet description and special features
   */
  description?: string | null;
  /**
   * Special delivery or pickup instructions
   */
  specialInstructions?: string | null;
  /**
   * Tags for search and categorization (JSON array of strings)
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Organize products into hierarchical categories for easy browsing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  /**
   * Category name (e.g., "Main Dishes", "Beverages", "Desserts")
   */
  name: string;
  /**
   * URL-friendly version of the name (auto-generated if empty)
   */
  slug: string;
  /**
   * Category description for customers
   */
  description?: string | null;
  /**
   * Parent category (leave empty for top-level categories)
   */
  parentCategory?: (number | null) | ProductCategory;
  /**
   * Hierarchy level (1 = top level, 2 = subcategory, etc.)
   */
  categoryLevel?: number | null;
  /**
   * Materialized path for efficient queries (auto-generated)
   */
  categoryPath?: string | null;
  /**
   * Order for displaying categories (lower numbers appear first)
   */
  displayOrder?: number | null;
  /**
   * Whether the category is currently active
   */
  isActive?: boolean | null;
  /**
   * Whether to feature this category prominently
   */
  isFeatured?: boolean | null;
  /**
   * Visual elements for the category
   */
  media?: {
    /**
     * Category icon (SVG preferred)
     */
    icon?: (number | null) | Media;
    /**
     * Banner image for category pages
     */
    bannerImage?: (number | null) | Media;
    /**
     * Thumbnail for category listings
     */
    thumbnailImage?: (number | null) | Media;
  };
  /**
   * Visual styling options
   */
  styling?: {
    /**
     * Hex color code for category theme (e.g., #FF6B35)
     */
    colorTheme?: string | null;
    /**
     * Background color for category cards
     */
    backgroundColor?: string | null;
    /**
     * Text color for category elements
     */
    textColor?: string | null;
    /**
     * Colors for gradient backgrounds (JSON array of hex color strings)
     */
    gradientColors?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Category-specific attributes and restrictions
   */
  attributes?: {
    /**
     * Type of products in this category
     */
    categoryType?:
      | (
          | 'food'
          | 'beverages'
          | 'desserts'
          | 'snacks'
          | 'groceries'
          | 'pharmacy'
          | 'personal_care'
          | 'household'
          | 'other'
        )
      | null;
    /**
     * Dietary attributes commonly found in this category (JSON array of strings)
     */
    dietaryTags?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Age restriction for products in this category
     */
    ageRestriction?: ('none' | '18_plus' | '21_plus') | null;
    /**
     * Whether products in this category require prescription
     */
    requiresPrescription?: boolean | null;
  };
  /**
   * Business rules and handling requirements
   */
  businessRules?: {
    /**
     * Whether products in this category can be customized
     */
    allowsCustomization?: boolean | null;
    /**
     * Whether products need special delivery handling
     */
    requiresSpecialHandling?: boolean | null;
    /**
     * Whether products in this category have expiration dates
     */
    hasExpirationDates?: boolean | null;
    /**
     * Whether products need refrigerated delivery
     */
    requiresRefrigeration?: boolean | null;
    /**
     * Maximum delivery time for products in this category (hours)
     */
    maxDeliveryTimeHours?: number | null;
  };
  /**
   * SEO optimization settings
   */
  seo?: {
    /**
     * SEO meta title
     */
    metaTitle?: string | null;
    /**
     * SEO meta description
     */
    metaDescription?: string | null;
    /**
     * SEO keywords for this category (JSON array of strings)
     */
    keywords?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Canonical URL for SEO
     */
    canonicalUrl?: string | null;
  };
  /**
   * Analytics and performance metrics
   */
  metrics?: {
    /**
     * Total number of products in this category
     */
    totalProducts?: number | null;
    /**
     * Total orders from this category
     */
    totalOrders?: number | null;
    /**
     * Average rating of products in this category
     */
    averageRating?: number | null;
    /**
     * Calculated popularity score
     */
    popularityScore?: number | null;
    /**
     * Number of times this category was viewed
     */
    viewCount?: number | null;
  };
  /**
   * Promotional campaigns and discounts
   */
  promotions?: {
    /**
     * Whether this category is currently being promoted
     */
    isPromotional?: boolean | null;
    /**
     * Promotional text to display with the category
     */
    promotionalText?: string | null;
    /**
     * Category-wide discount percentage
     */
    discountPercentage?: number | null;
    /**
     * When the promotion starts
     */
    promotionStartDate?: string | null;
    /**
     * When the promotion ends
     */
    promotionEndDate?: string | null;
  };
  /**
   * Availability and restriction settings
   */
  availability?: {
    /**
     * Hours when this category is available (JSON format)
     */
    availableHours?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Seasonal availability settings (JSON array of season objects)
     */
    seasonalAvailability?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Regional availability restrictions (JSON array of region objects)
     */
    regionRestrictions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage individual food items and products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Merchant/outlet that sells this product
   */
  merchant: number | Merchant;
  /**
   * Primary category for this product
   */
  primaryCategory: number | ProductCategory;
  /**
   * Product name (e.g., "Chicken Joy", "Big Mac", "Iced Coffee")
   */
  name: string;
  /**
   * URL-friendly version of the name (auto-generated if empty)
   */
  slug?: string | null;
  /**
   * Detailed product description for customers
   */
  description?: string | null;
  /**
   * Brief description for product listings
   */
  shortDescription?: string | null;
  /**
   * Pricing information and history
   */
  pricing: {
    /**
     * Base price in PHP
     */
    basePrice: number;
    /**
     * Discounted price (if on sale)
     */
    discountedPrice?: number | null;
    /**
     * Cost price for profit margin calculations
     */
    costPrice?: number | null;
  };
  /**
   * Product identification codes
   */
  identification?: {
    /**
     * Stock Keeping Unit (SKU)
     */
    sku?: string | null;
    /**
     * Product barcode
     */
    barcode?: string | null;
    /**
     * Internal product code
     */
    productCode?: string | null;
  };
  /**
   * Physical product attributes
   */
  physicalAttributes?: {
    /**
     * Product weight in grams
     */
    weightGrams?: number | null;
    dimensions?: {
      /**
       * Length in cm
       */
      length?: number | null;
      /**
       * Width in cm
       */
      width?: number | null;
      /**
       * Height in cm
       */
      height?: number | null;
    };
    /**
     * Volume in ml (for beverages)
     */
    volume?: number | null;
    /**
     * Serving size description (e.g., "1 piece", "250ml")
     */
    servingSize?: string | null;
  };
  /**
   * Nutritional information and facts
   */
  nutrition?: {
    /**
     * Calories per serving
     */
    calories?: number | null;
    macronutrients?: {
      /**
       * Protein in grams
       */
      protein?: number | null;
      /**
       * Carbohydrates in grams
       */
      carbohydrates?: number | null;
      /**
       * Fat in grams
       */
      fat?: number | null;
      /**
       * Fiber in grams
       */
      fiber?: number | null;
      /**
       * Sugar in grams
       */
      sugar?: number | null;
      /**
       * Sodium in mg
       */
      sodium?: number | null;
    };
  };
  /**
   * Dietary restrictions and allergen information
   */
  dietary?: {
    isVegetarian?: boolean | null;
    isVegan?: boolean | null;
    isGlutenFree?: boolean | null;
    isHalal?: boolean | null;
    isKosher?: boolean | null;
    isOrganic?: boolean | null;
    isDairyFree?: boolean | null;
    isNutFree?: boolean | null;
    spiceLevel?: ('none' | 'mild' | 'medium' | 'hot' | 'extra_hot') | null;
    /**
     * Known allergens present in this product (JSON array of strings)
     */
    allergens?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * List of ingredients in this product (JSON array of strings)
     */
    ingredients?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Availability and inventory management
   */
  availability?: {
    /**
     * Whether the product is currently available
     */
    isAvailable?: boolean | null;
    /**
     * Current stock quantity
     */
    stockQuantity?: number | null;
    /**
     * Alert when stock falls below this number
     */
    lowStockThreshold?: number | null;
    /**
     * Maximum quantity per order
     */
    maxOrderQuantity?: number | null;
    /**
     * Hours when this product is available (JSON format)
     */
    availableHours?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Seasonal availability periods (JSON array of objects with season, startDate, endDate)
     */
    seasonalAvailability?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Preparation and cooking information
   */
  preparation?: {
    /**
     * Time needed to prepare this item
     */
    preparationTimeMinutes?: number | null;
    cookingMethod?: ('grilled' | 'fried' | 'baked' | 'steamed' | 'boiled' | 'raw' | 'no_cooking' | 'other') | null;
    /**
     * Special preparation or handling instructions
     */
    specialInstructions?: string | null;
    requiresSpecialEquipment?: boolean | null;
  };
  /**
   * Visual content for the product
   */
  media?: {
    /**
     * Main product image
     */
    primaryImage?: (number | null) | Media;
    /**
     * Product video (preparation, presentation)
     */
    video?: (number | null) | Media;
  };
  /**
   * Product status and display settings
   */
  status?: {
    /**
     * Whether to feature this product prominently
     */
    isFeatured?: boolean | null;
    /**
     * Mark as new item
     */
    isNewItem?: boolean | null;
    /**
     * Mark as popular item
     */
    isPopular?: boolean | null;
    /**
     * Mark as recommended by chef/staff
     */
    isRecommended?: boolean | null;
    /**
     * Order for displaying products (lower numbers appear first)
     */
    displayOrder?: number | null;
  };
  /**
   * Performance analytics and metrics
   */
  metrics?: {
    /**
     * Average customer rating
     */
    averageRating?: number | null;
    /**
     * Total number of reviews
     */
    totalReviews?: number | null;
    /**
     * Total times ordered
     */
    totalOrders?: number | null;
    /**
     * Number of times viewed
     */
    viewCount?: number | null;
    /**
     * Calculated popularity score
     */
    popularityScore?: number | null;
    /**
     * Percentage of customers who reorder this item
     */
    reorderRate?: number | null;
  };
  /**
   * SEO optimization settings
   */
  seo?: {
    /**
     * SEO meta title
     */
    metaTitle?: string | null;
    /**
     * SEO meta description
     */
    metaDescription?: string | null;
  };
  /**
   * Product tags for search and categorization (JSON array of strings)
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes about the product
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'user-events';
        value: number | UserEvent;
      } | null)
    | ({
        relationTo: 'emergency-contacts';
        value: number | EmergencyContact;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'merchants';
        value: number | Merchant;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  middleName?: T;
  nameExtension?: T;
  username?: T;
  gender?: T;
  civilStatus?: T;
  nationality?: T;
  birthDate?: T;
  placeOfBirth?: T;
  completeAddress?: T;
  role?: T;
  isActive?: T;
  lastLogin?: T;
  profilePicture?: T;
  activeAddress?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  user?: T;
  srn?: T;
  couponCode?: T;
  enrollmentDate?: T;
  currentLevel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  user?: T;
  adminLevel?: T;
  systemPermissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-events_select".
 */
export interface UserEventsSelect<T extends boolean = true> {
  user?: T;
  eventType?: T;
  eventData?: T;
  triggeredBy?: T;
  timestamp?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-contacts_select".
 */
export interface EmergencyContactsSelect<T extends boolean = true> {
  user?: T;
  firstName?: T;
  middleName?: T;
  lastName?: T;
  contactNumber?: T;
  relationship?: T;
  completeAddress?: T;
  isPrimary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  user?: T;
  formatted_address?: T;
  google_place_id?: T;
  street_number?: T;
  route?: T;
  subpremise?: T;
  barangay?: T;
  locality?: T;
  administrative_area_level_2?: T;
  administrative_area_level_1?: T;
  country?: T;
  postal_code?: T;
  latitude?: T;
  longitude?: T;
  address_type?: T;
  is_default?: T;
  is_verified?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinaryPublicId?: T;
  cloudinaryURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  author?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyword?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  businessName?: T;
  legalName?: T;
  businessRegistrationNumber?: T;
  taxIdentificationNumber?: T;
  primaryContactEmail?: T;
  primaryContactPhone?: T;
  websiteUrl?: T;
  businessType?: T;
  cuisineTypes?: T;
  isActive?: T;
  verificationStatus?: T;
  onboardingDate?: T;
  averageRating?: T;
  totalReviews?: T;
  totalOrders?: T;
  totalMerchants?: T;
  businessLicense?: T;
  taxCertificate?: T;
  logo?: T;
  bankAccountName?: T;
  bankAccountNumber?: T;
  bankName?: T;
  description?: T;
  operatingHours?: T;
  socialMediaLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        website?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchants_select".
 */
export interface MerchantsSelect<T extends boolean = true> {
  vendor?: T;
  outletName?: T;
  outletCode?: T;
  address?:
    | T
    | {
        streetAddress?: T;
        barangay?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        country?: T;
      };
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        deliveryRadiusKm?: T;
      };
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        managerName?: T;
        managerPhone?: T;
      };
  isActive?: T;
  isAcceptingOrders?: T;
  operationalStatus?: T;
  operatingHours?: T;
  specialHours?: T;
  deliverySettings?:
    | T
    | {
        minimumOrderAmount?: T;
        deliveryFee?: T;
        freeDeliveryThreshold?: T;
        estimatedDeliveryTimeMinutes?: T;
        maxDeliveryTimeMinutes?: T;
      };
  media?:
    | T
    | {
        thumbnail?: T;
        storeFrontImage?: T;
        interiorImages?: T;
        menuImages?: T;
      };
  description?: T;
  specialInstructions?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parentCategory?: T;
  categoryLevel?: T;
  categoryPath?: T;
  displayOrder?: T;
  isActive?: T;
  isFeatured?: T;
  media?:
    | T
    | {
        icon?: T;
        bannerImage?: T;
        thumbnailImage?: T;
      };
  styling?:
    | T
    | {
        colorTheme?: T;
        backgroundColor?: T;
        textColor?: T;
        gradientColors?: T;
      };
  attributes?:
    | T
    | {
        categoryType?: T;
        dietaryTags?: T;
        ageRestriction?: T;
        requiresPrescription?: T;
      };
  businessRules?:
    | T
    | {
        allowsCustomization?: T;
        requiresSpecialHandling?: T;
        hasExpirationDates?: T;
        requiresRefrigeration?: T;
        maxDeliveryTimeHours?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
      };
  metrics?:
    | T
    | {
        totalProducts?: T;
        totalOrders?: T;
        averageRating?: T;
        popularityScore?: T;
        viewCount?: T;
      };
  promotions?:
    | T
    | {
        isPromotional?: T;
        promotionalText?: T;
        discountPercentage?: T;
        promotionStartDate?: T;
        promotionEndDate?: T;
      };
  availability?:
    | T
    | {
        availableHours?: T;
        seasonalAvailability?: T;
        regionRestrictions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  merchant?: T;
  primaryCategory?: T;
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  pricing?:
    | T
    | {
        basePrice?: T;
        discountedPrice?: T;
        costPrice?: T;
      };
  identification?:
    | T
    | {
        sku?: T;
        barcode?: T;
        productCode?: T;
      };
  physicalAttributes?:
    | T
    | {
        weightGrams?: T;
        dimensions?:
          | T
          | {
              length?: T;
              width?: T;
              height?: T;
            };
        volume?: T;
        servingSize?: T;
      };
  nutrition?:
    | T
    | {
        calories?: T;
        macronutrients?:
          | T
          | {
              protein?: T;
              carbohydrates?: T;
              fat?: T;
              fiber?: T;
              sugar?: T;
              sodium?: T;
            };
      };
  dietary?:
    | T
    | {
        isVegetarian?: T;
        isVegan?: T;
        isGlutenFree?: T;
        isHalal?: T;
        isKosher?: T;
        isOrganic?: T;
        isDairyFree?: T;
        isNutFree?: T;
        spiceLevel?: T;
        allergens?: T;
        ingredients?: T;
      };
  availability?:
    | T
    | {
        isAvailable?: T;
        stockQuantity?: T;
        lowStockThreshold?: T;
        maxOrderQuantity?: T;
        availableHours?: T;
        seasonalAvailability?: T;
      };
  preparation?:
    | T
    | {
        preparationTimeMinutes?: T;
        cookingMethod?: T;
        specialInstructions?: T;
        requiresSpecialEquipment?: T;
      };
  media?:
    | T
    | {
        primaryImage?: T;
        video?: T;
      };
  status?:
    | T
    | {
        isFeatured?: T;
        isNewItem?: T;
        isPopular?: T;
        isRecommended?: T;
        displayOrder?: T;
      };
  metrics?:
    | T
    | {
        averageRating?: T;
        totalReviews?: T;
        totalOrders?: T;
        viewCount?: T;
        popularityScore?: T;
        reorderRate?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  tags?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}