/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  boolean,
  numeric,
  jsonb,
  type AnyPgColumn,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_gender = pgEnum('enum_users_gender', [
  'male',
  'female',
  'other',
  'prefer_not_to_say',
])
export const enum_users_civil_status = pgEnum('enum_users_civil_status', [
  'single',
  'married',
  'divorced',
  'widowed',
  'separated',
])
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'customer', 'service', 'vendor'])
export const enum_customers_current_level = pgEnum('enum_customers_current_level', [
  'beginner',
  'intermediate',
  'advanced',
])
export const enum_admins_admin_level = pgEnum('enum_admins_admin_level', [
  'system',
  'department',
  'content',
])
export const enum_user_events_event_type = pgEnum('enum_user_events_event_type', [
  'USER_CREATED',
  'ROLE_CHANGED',
  'PROFILE_UPDATED',
  'USER_DEACTIVATED',
  'USER_REACTIVATED',
  'LOGIN_SUCCESS',
  'LOGIN_FAILED',
  'PASSWORD_CHANGED',
])
export const enum_emergency_contacts_relationship = pgEnum('enum_emergency_contacts_relationship', [
  'parent',
  'spouse',
  'sibling',
  'child',
  'guardian',
  'friend',
  'relative',
  'other',
])
export const enum_addresses_geocoding_accuracy = pgEnum('enum_addresses_geocoding_accuracy', [
  'ROOFTOP',
  'RANGE_INTERPOLATED',
  'GEOMETRIC_CENTER',
  'APPROXIMATE',
])
export const enum_addresses_coordinate_source = pgEnum('enum_addresses_coordinate_source', [
  'GPS',
  'GOOGLE_GEOCODING',
  'MANUAL',
  'ESTIMATED',
])
export const enum_addresses_verification_method = pgEnum('enum_addresses_verification_method', [
  'GPS_CONFIRMED',
  'DELIVERY_CONFIRMED',
  'USER_CONFIRMED',
  'UNVERIFIED',
])
export const enum_addresses_address_type = pgEnum('enum_addresses_address_type', [
  'home',
  'work',
  'billing',
  'shipping',
  'pickup',
  'delivery',
])
export const enum_posts_status = pgEnum('enum_posts_status', ['draft', 'published'])
export const enum__posts_v_version_status = pgEnum('enum__posts_v_version_status', [
  'draft',
  'published',
])
export const enum_vendors_business_type = pgEnum('enum_vendors_business_type', [
  'restaurant',
  'fast_food',
  'grocery',
  'pharmacy',
  'convenience',
  'bakery',
  'coffee_shop',
  'other',
])
export const enum_vendors_verification_status = pgEnum('enum_vendors_verification_status', [
  'pending',
  'verified',
  'rejected',
  'suspended',
])
export const enum_merchants_operational_status = pgEnum('enum_merchants_operational_status', [
  'open',
  'closed',
  'busy',
  'temp_closed',
  'maintenance',
])
export const enum_prod_categories_attributes_category_type = pgEnum(
  'enum_prod_categories_attributes_category_type',
  [
    'food',
    'beverages',
    'desserts',
    'snacks',
    'groceries',
    'pharmacy',
    'personal_care',
    'household',
    'other',
  ],
)
export const enum_prod_categories_attributes_age_restriction = pgEnum(
  'enum_prod_categories_attributes_age_restriction',
  ['none', '18_plus', '21_plus'],
)
export const enum_products_dietary_spice_level = pgEnum('enum_products_dietary_spice_level', [
  'none',
  'mild',
  'medium',
  'hot',
  'extra_hot',
])
export const enum_products_preparation_cooking_method = pgEnum(
  'enum_products_preparation_cooking_method',
  ['grilled', 'fried', 'baked', 'steamed', 'boiled', 'raw', 'no_cooking', 'other'],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => ({
    _orderIdx: index('users_sessions_order_idx').on(columns._order),
    _parentIDIdx: index('users_sessions_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    firstName: varchar('first_name').notNull(),
    lastName: varchar('last_name').notNull(),
    middleName: varchar('middle_name'),
    nameExtension: varchar('name_extension'),
    username: varchar('username'),
    gender: enum_users_gender('gender'),
    civilStatus: enum_users_civil_status('civil_status'),
    nationality: varchar('nationality'),
    birthDate: timestamp('birth_date', { mode: 'string', withTimezone: true, precision: 3 }),
    placeOfBirth: varchar('place_of_birth'),
    completeAddress: varchar('complete_address'),
    role: enum_users_role('role').notNull().default('customer'),
    isActive: boolean('is_active').default(true),
    lastLogin: timestamp('last_login', { mode: 'string', withTimezone: true, precision: 3 }),
    profilePicture: integer('profile_picture_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    enableAPIKey: boolean('enable_a_p_i_key'),
    apiKey: varchar('api_key'),
    apiKeyIndex: varchar('api_key_index'),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    users_username_idx: uniqueIndex('users_username_idx').on(columns.username),
    users_profile_picture_idx: index('users_profile_picture_idx').on(columns.profilePicture),
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
  }),
)

export const customers = pgTable(
  'customers',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    srn: varchar('srn').notNull(),
    couponCode: varchar('coupon_code'),
    enrollmentDate: timestamp('enrollment_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    currentLevel: enum_customers_current_level('current_level').default('beginner'),
    activeAddress: integer('active_address_id').references(() => addresses.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    customers_user_idx: uniqueIndex('customers_user_idx').on(columns.user),
    customers_srn_idx: uniqueIndex('customers_srn_idx').on(columns.srn),
    customers_active_address_idx: index('customers_active_address_idx').on(columns.activeAddress),
    customers_updated_at_idx: index('customers_updated_at_idx').on(columns.updatedAt),
    customers_created_at_idx: index('customers_created_at_idx').on(columns.createdAt),
  }),
)

export const admins = pgTable(
  'admins',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    adminLevel: enum_admins_admin_level('admin_level').notNull().default('content'),
    systemPermissions: jsonb('system_permissions'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    admins_user_idx: uniqueIndex('admins_user_idx').on(columns.user),
    admins_updated_at_idx: index('admins_updated_at_idx').on(columns.updatedAt),
    admins_created_at_idx: index('admins_created_at_idx').on(columns.createdAt),
  }),
)

export const user_events = pgTable(
  'user_events',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    eventType: enum_user_events_event_type('event_type').notNull(),
    eventData: jsonb('event_data').notNull(),
    triggeredBy: integer('triggered_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    timestamp: timestamp('timestamp', { mode: 'string', withTimezone: true, precision: 3 }),
    ipAddress: varchar('ip_address'),
    userAgent: varchar('user_agent'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    user_events_user_idx: index('user_events_user_idx').on(columns.user),
    user_events_triggered_by_idx: index('user_events_triggered_by_idx').on(columns.triggeredBy),
    user_events_updated_at_idx: index('user_events_updated_at_idx').on(columns.updatedAt),
    user_events_created_at_idx: index('user_events_created_at_idx').on(columns.createdAt),
  }),
)

export const emergency_contacts = pgTable(
  'emergency_contacts',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    firstName: varchar('first_name').notNull(),
    middleName: varchar('middle_name'),
    lastName: varchar('last_name').notNull(),
    contactNumber: varchar('contact_number').notNull(),
    relationship: enum_emergency_contacts_relationship('relationship').notNull(),
    completeAddress: varchar('complete_address').notNull(),
    isPrimary: boolean('is_primary').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    emergency_contacts_user_idx: index('emergency_contacts_user_idx').on(columns.user),
    emergency_contacts_updated_at_idx: index('emergency_contacts_updated_at_idx').on(
      columns.updatedAt,
    ),
    emergency_contacts_created_at_idx: index('emergency_contacts_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const addresses = pgTable(
  'addresses',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    formatted_address: varchar('formatted_address').notNull(),
    google_place_id: varchar('google_place_id'),
    street_number: varchar('street_number'),
    route: varchar('route'),
    subpremise: varchar('subpremise'),
    barangay: varchar('barangay'),
    locality: varchar('locality'),
    administrative_area_level_2: varchar('administrative_area_level_2'),
    administrative_area_level_1: varchar('administrative_area_level_1'),
    country: varchar('country').default('Philippines'),
    postal_code: varchar('postal_code'),
    latitude: numeric('latitude'),
    longitude: numeric('longitude'),
    coordinates: jsonb('coordinates'),
    altitude: numeric('altitude'),
    address_quality_score: numeric('address_quality_score'),
    geocoding_accuracy: enum_addresses_geocoding_accuracy('geocoding_accuracy'),
    coordinate_source:
      enum_addresses_coordinate_source('coordinate_source').default('GOOGLE_GEOCODING'),
    last_geocoded_at: timestamp('last_geocoded_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    verification_method:
      enum_addresses_verification_method('verification_method').default('UNVERIFIED'),
    address_boundary: jsonb('address_boundary'),
    service_radius_meters: numeric('service_radius_meters'),
    accessibility_notes: varchar('accessibility_notes'),
    landmark_description: varchar('landmark_description'),
    address_type: enum_addresses_address_type('address_type').notNull().default('home'),
    is_default: boolean('is_default').default(false),
    is_verified: boolean('is_verified').default(false),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    addresses_user_idx: index('addresses_user_idx').on(columns.user),
    addresses_updated_at_idx: index('addresses_updated_at_idx').on(columns.updatedAt),
    addresses_created_at_idx: index('addresses_created_at_idx').on(columns.createdAt),
    user_idx: index('user_idx').on(columns.user),
    latitude_longitude_idx: index('latitude_longitude_idx').on(columns.latitude, columns.longitude),
    locality_administrative_area_level_1_idx: index('locality_administrative_area_level_1_idx').on(
      columns.locality,
      columns.administrative_area_level_1,
    ),
    postal_code_idx: index('postal_code_idx').on(columns.postal_code),
    google_place_id_idx: index('google_place_id_idx').on(columns.google_place_id),
    address_quality_score_idx: index('address_quality_score_idx').on(columns.address_quality_score),
    is_verified_idx: index('is_verified_idx').on(columns.is_verified),
    geocoding_accuracy_idx: index('geocoding_accuracy_idx').on(columns.geocoding_accuracy),
    coordinate_source_idx: index('coordinate_source_idx').on(columns.coordinate_source),
    verification_method_idx: index('verification_method_idx').on(columns.verification_method),
  }),
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt'),
    cloudinaryPublicId: varchar('cloudinary_public_id'),
    cloudinaryURL: varchar('cloudinary_u_r_l'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
  }),
)

export const posts_tags = pgTable(
  'posts_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag'),
  },
  (columns) => ({
    _orderIdx: index('posts_tags_order_idx').on(columns._order),
    _parentIDIdx: index('posts_tags_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [posts.id],
      name: 'posts_tags_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    content: jsonb('content'),
    excerpt: varchar('excerpt'),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    status: enum_posts_status('status').default('draft'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    author: integer('author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    seo_focusKeyword: varchar('seo_focus_keyword'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_posts_status('_status').default('draft'),
  },
  (columns) => ({
    posts_slug_idx: uniqueIndex('posts_slug_idx').on(columns.slug),
    posts_featured_image_idx: index('posts_featured_image_idx').on(columns.featuredImage),
    posts_author_idx: index('posts_author_idx').on(columns.author),
    posts_updated_at_idx: index('posts_updated_at_idx').on(columns.updatedAt),
    posts_created_at_idx: index('posts_created_at_idx').on(columns.createdAt),
    posts__status_idx: index('posts__status_idx').on(columns._status),
  }),
)

export const _posts_v_version_tags = pgTable(
  '_posts_v_version_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    tag: varchar('tag'),
    _uuid: varchar('_uuid'),
  },
  (columns) => ({
    _orderIdx: index('_posts_v_version_tags_order_idx').on(columns._order),
    _parentIDIdx: index('_posts_v_version_tags_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_version_tags_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const _posts_v = pgTable(
  '_posts_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => posts.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_content: jsonb('version_content'),
    version_excerpt: varchar('version_excerpt'),
    version_featuredImage: integer('version_featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_status: enum__posts_v_version_status('version_status').default('draft'),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_author: integer('version_author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    version_seo_title: varchar('version_seo_title'),
    version_seo_description: varchar('version_seo_description'),
    version_seo_focusKeyword: varchar('version_seo_focus_keyword'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__posts_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => ({
    _posts_v_parent_idx: index('_posts_v_parent_idx').on(columns.parent),
    _posts_v_version_version_slug_idx: index('_posts_v_version_version_slug_idx').on(
      columns.version_slug,
    ),
    _posts_v_version_version_featured_image_idx: index(
      '_posts_v_version_version_featured_image_idx',
    ).on(columns.version_featuredImage),
    _posts_v_version_version_author_idx: index('_posts_v_version_version_author_idx').on(
      columns.version_author,
    ),
    _posts_v_version_version_updated_at_idx: index('_posts_v_version_version_updated_at_idx').on(
      columns.version_updatedAt,
    ),
    _posts_v_version_version_created_at_idx: index('_posts_v_version_version_created_at_idx').on(
      columns.version_createdAt,
    ),
    _posts_v_version_version__status_idx: index('_posts_v_version_version__status_idx').on(
      columns.version__status,
    ),
    _posts_v_created_at_idx: index('_posts_v_created_at_idx').on(columns.createdAt),
    _posts_v_updated_at_idx: index('_posts_v_updated_at_idx').on(columns.updatedAt),
    _posts_v_latest_idx: index('_posts_v_latest_idx').on(columns.latest),
  }),
)

export const vendors = pgTable(
  'vendors',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    businessName: varchar('business_name').notNull(),
    legalName: varchar('legal_name').notNull(),
    businessRegistrationNumber: varchar('business_registration_number').notNull(),
    taxIdentificationNumber: varchar('tax_identification_number'),
    primaryContactEmail: varchar('primary_contact_email').notNull(),
    primaryContactPhone: varchar('primary_contact_phone').notNull(),
    websiteUrl: varchar('website_url'),
    businessType: enum_vendors_business_type('business_type').notNull(),
    cuisineTypes: jsonb('cuisine_types'),
    isActive: boolean('is_active').default(true),
    verificationStatus: enum_vendors_verification_status('verification_status')
      .notNull()
      .default('pending'),
    onboardingDate: timestamp('onboarding_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    averageRating: numeric('average_rating').default('0'),
    totalReviews: numeric('total_reviews').default('0'),
    totalOrders: numeric('total_orders').default('0'),
    totalMerchants: numeric('total_merchants').default('0'),
    businessLicense: integer('business_license_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    taxCertificate: integer('tax_certificate_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    bankAccountName: varchar('bank_account_name'),
    bankAccountNumber: varchar('bank_account_number'),
    bankName: varchar('bank_name'),
    description: varchar('description'),
    operatingHours: jsonb('operating_hours'),
    socialMediaLinks_facebook: varchar('social_media_links_facebook'),
    socialMediaLinks_instagram: varchar('social_media_links_instagram'),
    socialMediaLinks_twitter: varchar('social_media_links_twitter'),
    socialMediaLinks_website: varchar('social_media_links_website'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    vendors_user_idx: index('vendors_user_idx').on(columns.user),
    vendors_business_registration_number_idx: uniqueIndex(
      'vendors_business_registration_number_idx',
    ).on(columns.businessRegistrationNumber),
    vendors_tax_identification_number_idx: uniqueIndex('vendors_tax_identification_number_idx').on(
      columns.taxIdentificationNumber,
    ),
    vendors_business_license_idx: index('vendors_business_license_idx').on(columns.businessLicense),
    vendors_tax_certificate_idx: index('vendors_tax_certificate_idx').on(columns.taxCertificate),
    vendors_logo_idx: index('vendors_logo_idx').on(columns.logo),
    vendors_updated_at_idx: index('vendors_updated_at_idx').on(columns.updatedAt),
    vendors_created_at_idx: index('vendors_created_at_idx').on(columns.createdAt),
  }),
)

export const merchants = pgTable(
  'merchants',
  {
    id: serial('id').primaryKey(),
    vendor: integer('vendor_id')
      .notNull()
      .references(() => vendors.id, {
        onDelete: 'set null',
      }),
    outletName: varchar('outlet_name').notNull(),
    outletCode: varchar('outlet_code').notNull(),
    contactInfo_phone: varchar('contact_info_phone'),
    contactInfo_email: varchar('contact_info_email'),
    contactInfo_managerName: varchar('contact_info_manager_name'),
    contactInfo_managerPhone: varchar('contact_info_manager_phone'),
    isActive: boolean('is_active').default(true),
    isAcceptingOrders: boolean('is_accepting_orders').default(true),
    operationalStatus: enum_merchants_operational_status('operational_status').default('open'),
    operatingHours: jsonb('operating_hours'),
    specialHours: jsonb('special_hours'),
    deliverySettings_minimumOrderAmount: numeric('delivery_settings_minimum_order_amount').default(
      '0',
    ),
    deliverySettings_deliveryFee: numeric('delivery_settings_delivery_fee').default('0'),
    deliverySettings_freeDeliveryThreshold: numeric('delivery_settings_free_delivery_threshold'),
    deliverySettings_estimatedDeliveryTimeMinutes: numeric(
      'delivery_settings_estimated_delivery_time_minutes',
    ).default('30'),
    deliverySettings_maxDeliveryTimeMinutes: numeric(
      'delivery_settings_max_delivery_time_minutes',
    ).default('60'),
    media_thumbnail: integer('media_thumbnail_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    media_storeFrontImage: integer('media_store_front_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    media_interiorImages: jsonb('media_interior_images'),
    media_menuImages: jsonb('media_menu_images'),
    description: varchar('description'),
    specialInstructions: varchar('special_instructions'),
    tags: jsonb('tags'),
    activeAddress: integer('active_address_id').references(() => addresses.id, {
      onDelete: 'set null',
    }),
    merchant_latitude: numeric('merchant_latitude'),
    merchant_longitude: numeric('merchant_longitude'),
    location_accuracy_radius: numeric('location_accuracy_radius'),
    delivery_radius_meters: numeric('delivery_radius_meters').default('5000'),
    max_delivery_radius_meters: numeric('max_delivery_radius_meters').default('10000'),
    min_order_amount: numeric('min_order_amount'),
    delivery_fee_base: numeric('delivery_fee_base'),
    delivery_fee_per_km: numeric('delivery_fee_per_km'),
    free_delivery_threshold: numeric('free_delivery_threshold'),
    merchant_coordinates: jsonb('merchant_coordinates'),
    service_area_geometry: jsonb('service_area_geometry'),
    priority_zones_geometry: jsonb('priority_zones_geometry'),
    restricted_areas_geometry: jsonb('restricted_areas_geometry'),
    delivery_zones_geometry: jsonb('delivery_zones_geometry'),
    service_area: jsonb('service_area'),
    priority_zones: jsonb('priority_zones'),
    restricted_areas: jsonb('restricted_areas'),
    delivery_zones: jsonb('delivery_zones'),
    avg_delivery_time_minutes: numeric('avg_delivery_time_minutes'),
    delivery_success_rate: numeric('delivery_success_rate'),
    peak_hours_multiplier: numeric('peak_hours_multiplier').default('1'),
    delivery_hours: jsonb('delivery_hours'),
    is_currently_delivering: boolean('is_currently_delivering').default(true),
    next_available_slot: timestamp('next_available_slot', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    merchants_vendor_idx: index('merchants_vendor_idx').on(columns.vendor),
    merchants_outlet_code_idx: uniqueIndex('merchants_outlet_code_idx').on(columns.outletCode),
    merchants_media_media_thumbnail_idx: index('merchants_media_media_thumbnail_idx').on(
      columns.media_thumbnail,
    ),
    merchants_media_media_store_front_image_idx: index(
      'merchants_media_media_store_front_image_idx',
    ).on(columns.media_storeFrontImage),
    merchants_active_address_idx: index('merchants_active_address_idx').on(columns.activeAddress),
    merchants_updated_at_idx: index('merchants_updated_at_idx').on(columns.updatedAt),
    merchants_created_at_idx: index('merchants_created_at_idx').on(columns.createdAt),
    vendor_idx: index('vendor_idx').on(columns.vendor),
    outletCode_idx: index('outletCode_idx').on(columns.outletCode),
    isActive_isAcceptingOrders_idx: index('isActive_isAcceptingOrders_idx').on(
      columns.isActive,
      columns.isAcceptingOrders,
    ),
    operationalStatus_idx: index('operationalStatus_idx').on(columns.operationalStatus),
    delivery_radius_meters_idx: index('delivery_radius_meters_idx').on(
      columns.delivery_radius_meters,
    ),
    is_currently_delivering_idx: index('is_currently_delivering_idx').on(
      columns.is_currently_delivering,
    ),
    avg_delivery_time_minutes_idx: index('avg_delivery_time_minutes_idx').on(
      columns.avg_delivery_time_minutes,
    ),
    delivery_success_rate_idx: index('delivery_success_rate_idx').on(columns.delivery_success_rate),
  }),
)

export const prod_categories = pgTable(
  'prod_categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    parentCategory: integer('parent_category_id').references(
      (): AnyPgColumn => prod_categories.id,
      {
        onDelete: 'set null',
      },
    ),
    categoryLevel: numeric('category_level').default('1'),
    categoryPath: varchar('category_path'),
    displayOrder: numeric('display_order').default('0'),
    isActive: boolean('is_active').default(true),
    isFeatured: boolean('is_featured').default(false),
    media_icon: integer('media_icon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    media_bannerImage: integer('media_banner_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    media_thumbnailImage: integer('media_thumbnail_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    styling_colorTheme: varchar('styling_color_theme'),
    styling_backgroundColor: varchar('styling_background_color'),
    styling_textColor: varchar('styling_text_color'),
    styling_gradientColors: jsonb('styling_gradient_colors'),
    attributes_categoryType: enum_prod_categories_attributes_category_type(
      'attributes_category_type',
    ),
    attributes_dietaryTags: jsonb('attributes_dietary_tags'),
    attributes_ageRestriction: enum_prod_categories_attributes_age_restriction(
      'attributes_age_restriction',
    ).default('none'),
    attributes_requiresPrescription: boolean('attributes_requires_prescription').default(false),
    businessRules_allowsCustomization: boolean('business_rules_allows_customization').default(true),
    businessRules_requiresSpecialHandling: boolean(
      'business_rules_requires_special_handling',
    ).default(false),
    businessRules_hasExpirationDates: boolean('business_rules_has_expiration_dates').default(false),
    businessRules_requiresRefrigeration: boolean('business_rules_requires_refrigeration').default(
      false,
    ),
    businessRules_maxDeliveryTimeHours: numeric('business_rules_max_delivery_time_hours'),
    seo_metaTitle: varchar('seo_meta_title'),
    seo_metaDescription: varchar('seo_meta_description'),
    seo_keywords: jsonb('seo_keywords'),
    seo_canonicalUrl: varchar('seo_canonical_url'),
    metrics_totalProducts: numeric('metrics_total_products').default('0'),
    metrics_totalOrders: numeric('metrics_total_orders').default('0'),
    metrics_averageRating: numeric('metrics_average_rating').default('0'),
    metrics_popularityScore: numeric('metrics_popularity_score').default('0'),
    metrics_viewCount: numeric('metrics_view_count').default('0'),
    promotions_isPromotional: boolean('promotions_is_promotional').default(false),
    promotions_promotionalText: varchar('promotions_promotional_text'),
    promotions_discountPercentage: numeric('promotions_discount_percentage'),
    promotions_promotionStartDate: timestamp('promotions_promotion_start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    promotions_promotionEndDate: timestamp('promotions_promotion_end_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    availability_availableHours: jsonb('availability_available_hours'),
    availability_seasonalAvailability: jsonb('availability_seasonal_availability'),
    availability_regionRestrictions: jsonb('availability_region_restrictions'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    prod_categories_slug_idx: uniqueIndex('prod_categories_slug_idx').on(columns.slug),
    prod_categories_parent_category_idx: index('prod_categories_parent_category_idx').on(
      columns.parentCategory,
    ),
    prod_categories_media_media_icon_idx: index('prod_categories_media_media_icon_idx').on(
      columns.media_icon,
    ),
    prod_categories_media_media_banner_image_idx: index(
      'prod_categories_media_media_banner_image_idx',
    ).on(columns.media_bannerImage),
    prod_categories_media_media_thumbnail_image_idx: index(
      'prod_categories_media_media_thumbnail_image_idx',
    ).on(columns.media_thumbnailImage),
    prod_categories_updated_at_idx: index('prod_categories_updated_at_idx').on(columns.updatedAt),
    prod_categories_created_at_idx: index('prod_categories_created_at_idx').on(columns.createdAt),
  }),
)

export const products = pgTable(
  'products',
  {
    id: serial('id').primaryKey(),
    merchant: integer('merchant_id')
      .notNull()
      .references(() => merchants.id, {
        onDelete: 'set null',
      }),
    primaryCategory: integer('primary_category_id')
      .notNull()
      .references(() => prod_categories.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    slug: varchar('slug'),
    description: varchar('description'),
    shortDescription: varchar('short_description'),
    pricing_basePrice: numeric('pricing_base_price').notNull(),
    pricing_discountedPrice: numeric('pricing_discounted_price'),
    pricing_costPrice: numeric('pricing_cost_price'),
    identification_sku: varchar('identification_sku'),
    identification_barcode: varchar('identification_barcode'),
    identification_productCode: varchar('identification_product_code'),
    physicalAttributes_weightGrams: numeric('physical_attributes_weight_grams'),
    physicalAttributes_dimensions_length: numeric('physical_attributes_dimensions_length'),
    physicalAttributes_dimensions_width: numeric('physical_attributes_dimensions_width'),
    physicalAttributes_dimensions_height: numeric('physical_attributes_dimensions_height'),
    physicalAttributes_volume: numeric('physical_attributes_volume'),
    physicalAttributes_servingSize: varchar('physical_attributes_serving_size'),
    nutrition_calories: numeric('nutrition_calories'),
    nutrition_macronutrients_protein: numeric('nutrition_macronutrients_protein'),
    nutrition_macronutrients_carbohydrates: numeric('nutrition_macronutrients_carbohydrates'),
    nutrition_macronutrients_fat: numeric('nutrition_macronutrients_fat'),
    nutrition_macronutrients_fiber: numeric('nutrition_macronutrients_fiber'),
    nutrition_macronutrients_sugar: numeric('nutrition_macronutrients_sugar'),
    nutrition_macronutrients_sodium: numeric('nutrition_macronutrients_sodium'),
    dietary_isVegetarian: boolean('dietary_is_vegetarian').default(false),
    dietary_isVegan: boolean('dietary_is_vegan').default(false),
    dietary_isGlutenFree: boolean('dietary_is_gluten_free').default(false),
    dietary_isHalal: boolean('dietary_is_halal').default(false),
    dietary_isKosher: boolean('dietary_is_kosher').default(false),
    dietary_isOrganic: boolean('dietary_is_organic').default(false),
    dietary_isDairyFree: boolean('dietary_is_dairy_free').default(false),
    dietary_isNutFree: boolean('dietary_is_nut_free').default(false),
    dietary_spiceLevel: enum_products_dietary_spice_level('dietary_spice_level').default('none'),
    dietary_allergens: jsonb('dietary_allergens'),
    dietary_ingredients: jsonb('dietary_ingredients'),
    availability_isAvailable: boolean('availability_is_available').default(true),
    availability_stockQuantity: numeric('availability_stock_quantity'),
    availability_lowStockThreshold: numeric('availability_low_stock_threshold').default('5'),
    availability_maxOrderQuantity: numeric('availability_max_order_quantity'),
    availability_availableHours: jsonb('availability_available_hours'),
    availability_seasonalAvailability: jsonb('availability_seasonal_availability'),
    preparation_preparationTimeMinutes: numeric('preparation_preparation_time_minutes').default(
      '15',
    ),
    preparation_cookingMethod: enum_products_preparation_cooking_method(
      'preparation_cooking_method',
    ),
    preparation_specialInstructions: varchar('preparation_special_instructions'),
    preparation_requiresSpecialEquipment: boolean('preparation_requires_special_equipment').default(
      false,
    ),
    media_primaryImage: integer('media_primary_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    media_video: integer('media_video_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    status_isFeatured: boolean('status_is_featured').default(false),
    status_isNewItem: boolean('status_is_new_item').default(false),
    status_isPopular: boolean('status_is_popular').default(false),
    status_isRecommended: boolean('status_is_recommended').default(false),
    status_displayOrder: numeric('status_display_order').default('0'),
    metrics_averageRating: numeric('metrics_average_rating').default('0'),
    metrics_totalReviews: numeric('metrics_total_reviews').default('0'),
    metrics_totalOrders: numeric('metrics_total_orders').default('0'),
    metrics_viewCount: numeric('metrics_view_count').default('0'),
    metrics_popularityScore: numeric('metrics_popularity_score').default('0'),
    metrics_reorderRate: numeric('metrics_reorder_rate').default('0'),
    seo_metaTitle: varchar('seo_meta_title'),
    seo_metaDescription: varchar('seo_meta_description'),
    tags: jsonb('tags'),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    products_merchant_idx: index('products_merchant_idx').on(columns.merchant),
    products_primary_category_idx: index('products_primary_category_idx').on(
      columns.primaryCategory,
    ),
    products_slug_idx: uniqueIndex('products_slug_idx').on(columns.slug),
    products_identification_identification_sku_idx: uniqueIndex(
      'products_identification_identification_sku_idx',
    ).on(columns.identification_sku),
    products_media_media_primary_image_idx: index('products_media_media_primary_image_idx').on(
      columns.media_primaryImage,
    ),
    products_media_media_video_idx: index('products_media_media_video_idx').on(columns.media_video),
    products_updated_at_idx: index('products_updated_at_idx').on(columns.updatedAt),
    products_created_at_idx: index('products_created_at_idx').on(columns.createdAt),
  }),
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    customersID: integer('customers_id'),
    adminsID: integer('admins_id'),
    'user-eventsID': integer('user_events_id'),
    'emergency-contactsID': integer('emergency_contacts_id'),
    addressesID: integer('addresses_id'),
    mediaID: integer('media_id'),
    postsID: integer('posts_id'),
    vendorsID: integer('vendors_id'),
    merchantsID: integer('merchants_id'),
    'product-categoriesID': integer('prod_categories_id'),
    productsID: integer('products_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_customers_id_idx: index(
      'payload_locked_documents_rels_customers_id_idx',
    ).on(columns.customersID),
    payload_locked_documents_rels_admins_id_idx: index(
      'payload_locked_documents_rels_admins_id_idx',
    ).on(columns.adminsID),
    payload_locked_documents_rels_user_events_id_idx: index(
      'payload_locked_documents_rels_user_events_id_idx',
    ).on(columns['user-eventsID']),
    payload_locked_documents_rels_emergency_contacts_id_idx: index(
      'payload_locked_documents_rels_emergency_contacts_id_idx',
    ).on(columns['emergency-contactsID']),
    payload_locked_documents_rels_addresses_id_idx: index(
      'payload_locked_documents_rels_addresses_id_idx',
    ).on(columns.addressesID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_posts_id_idx: index(
      'payload_locked_documents_rels_posts_id_idx',
    ).on(columns.postsID),
    payload_locked_documents_rels_vendors_id_idx: index(
      'payload_locked_documents_rels_vendors_id_idx',
    ).on(columns.vendorsID),
    payload_locked_documents_rels_merchants_id_idx: index(
      'payload_locked_documents_rels_merchants_id_idx',
    ).on(columns.merchantsID),
    payload_locked_documents_rels_prod_categories_id_idx: index(
      'payload_locked_documents_rels_prod_categories_id_idx',
    ).on(columns['product-categoriesID']),
    payload_locked_documents_rels_products_id_idx: index(
      'payload_locked_documents_rels_products_id_idx',
    ).on(columns.productsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    customersIdFk: foreignKey({
      columns: [columns['customersID']],
      foreignColumns: [customers.id],
      name: 'payload_locked_documents_rels_customers_fk',
    }).onDelete('cascade'),
    adminsIdFk: foreignKey({
      columns: [columns['adminsID']],
      foreignColumns: [admins.id],
      name: 'payload_locked_documents_rels_admins_fk',
    }).onDelete('cascade'),
    'user-eventsIdFk': foreignKey({
      columns: [columns['user-eventsID']],
      foreignColumns: [user_events.id],
      name: 'payload_locked_documents_rels_user_events_fk',
    }).onDelete('cascade'),
    'emergency-contactsIdFk': foreignKey({
      columns: [columns['emergency-contactsID']],
      foreignColumns: [emergency_contacts.id],
      name: 'payload_locked_documents_rels_emergency_contacts_fk',
    }).onDelete('cascade'),
    addressesIdFk: foreignKey({
      columns: [columns['addressesID']],
      foreignColumns: [addresses.id],
      name: 'payload_locked_documents_rels_addresses_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    vendorsIdFk: foreignKey({
      columns: [columns['vendorsID']],
      foreignColumns: [vendors.id],
      name: 'payload_locked_documents_rels_vendors_fk',
    }).onDelete('cascade'),
    merchantsIdFk: foreignKey({
      columns: [columns['merchantsID']],
      foreignColumns: [merchants.id],
      name: 'payload_locked_documents_rels_merchants_fk',
    }).onDelete('cascade'),
    'product-categoriesIdFk': foreignKey({
      columns: [columns['product-categoriesID']],
      foreignColumns: [prod_categories.id],
      name: 'payload_locked_documents_rels_product_categories_fk',
    }).onDelete('cascade'),
    productsIdFk: foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  profilePicture: one(media, {
    fields: [users.profilePicture],
    references: [media.id],
    relationName: 'profilePicture',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_customers = relations(customers, ({ one }) => ({
  user: one(users, {
    fields: [customers.user],
    references: [users.id],
    relationName: 'user',
  }),
  activeAddress: one(addresses, {
    fields: [customers.activeAddress],
    references: [addresses.id],
    relationName: 'activeAddress',
  }),
}))
export const relations_admins = relations(admins, ({ one }) => ({
  user: one(users, {
    fields: [admins.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_user_events = relations(user_events, ({ one }) => ({
  user: one(users, {
    fields: [user_events.user],
    references: [users.id],
    relationName: 'user',
  }),
  triggeredBy: one(users, {
    fields: [user_events.triggeredBy],
    references: [users.id],
    relationName: 'triggeredBy',
  }),
}))
export const relations_emergency_contacts = relations(emergency_contacts, ({ one }) => ({
  user: one(users, {
    fields: [emergency_contacts.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_addresses = relations(addresses, ({ one }) => ({
  user: one(users, {
    fields: [addresses.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_posts_tags = relations(posts_tags, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_tags._parentID],
    references: [posts.id],
    relationName: 'tags',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [posts.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  tags: many(posts_tags, {
    relationName: 'tags',
  }),
  author: one(users, {
    fields: [posts.author],
    references: [users.id],
    relationName: 'author',
  }),
}))
export const relations__posts_v_version_tags = relations(_posts_v_version_tags, ({ one }) => ({
  _parentID: one(_posts_v, {
    fields: [_posts_v_version_tags._parentID],
    references: [_posts_v.id],
    relationName: 'version_tags',
  }),
}))
export const relations__posts_v = relations(_posts_v, ({ one, many }) => ({
  parent: one(posts, {
    fields: [_posts_v.parent],
    references: [posts.id],
    relationName: 'parent',
  }),
  version_featuredImage: one(media, {
    fields: [_posts_v.version_featuredImage],
    references: [media.id],
    relationName: 'version_featuredImage',
  }),
  version_tags: many(_posts_v_version_tags, {
    relationName: 'version_tags',
  }),
  version_author: one(users, {
    fields: [_posts_v.version_author],
    references: [users.id],
    relationName: 'version_author',
  }),
}))
export const relations_vendors = relations(vendors, ({ one }) => ({
  user: one(users, {
    fields: [vendors.user],
    references: [users.id],
    relationName: 'user',
  }),
  businessLicense: one(media, {
    fields: [vendors.businessLicense],
    references: [media.id],
    relationName: 'businessLicense',
  }),
  taxCertificate: one(media, {
    fields: [vendors.taxCertificate],
    references: [media.id],
    relationName: 'taxCertificate',
  }),
  logo: one(media, {
    fields: [vendors.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations_merchants = relations(merchants, ({ one }) => ({
  vendor: one(vendors, {
    fields: [merchants.vendor],
    references: [vendors.id],
    relationName: 'vendor',
  }),
  media_thumbnail: one(media, {
    fields: [merchants.media_thumbnail],
    references: [media.id],
    relationName: 'media_thumbnail',
  }),
  media_storeFrontImage: one(media, {
    fields: [merchants.media_storeFrontImage],
    references: [media.id],
    relationName: 'media_storeFrontImage',
  }),
  activeAddress: one(addresses, {
    fields: [merchants.activeAddress],
    references: [addresses.id],
    relationName: 'activeAddress',
  }),
}))
export const relations_prod_categories = relations(prod_categories, ({ one }) => ({
  parentCategory: one(prod_categories, {
    fields: [prod_categories.parentCategory],
    references: [prod_categories.id],
    relationName: 'parentCategory',
  }),
  media_icon: one(media, {
    fields: [prod_categories.media_icon],
    references: [media.id],
    relationName: 'media_icon',
  }),
  media_bannerImage: one(media, {
    fields: [prod_categories.media_bannerImage],
    references: [media.id],
    relationName: 'media_bannerImage',
  }),
  media_thumbnailImage: one(media, {
    fields: [prod_categories.media_thumbnailImage],
    references: [media.id],
    relationName: 'media_thumbnailImage',
  }),
}))
export const relations_products = relations(products, ({ one }) => ({
  merchant: one(merchants, {
    fields: [products.merchant],
    references: [merchants.id],
    relationName: 'merchant',
  }),
  primaryCategory: one(prod_categories, {
    fields: [products.primaryCategory],
    references: [prod_categories.id],
    relationName: 'primaryCategory',
  }),
  media_primaryImage: one(media, {
    fields: [products.media_primaryImage],
    references: [media.id],
    relationName: 'media_primaryImage',
  }),
  media_video: one(media, {
    fields: [products.media_video],
    references: [media.id],
    relationName: 'media_video',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    customersID: one(customers, {
      fields: [payload_locked_documents_rels.customersID],
      references: [customers.id],
      relationName: 'customers',
    }),
    adminsID: one(admins, {
      fields: [payload_locked_documents_rels.adminsID],
      references: [admins.id],
      relationName: 'admins',
    }),
    'user-eventsID': one(user_events, {
      fields: [payload_locked_documents_rels['user-eventsID']],
      references: [user_events.id],
      relationName: 'user-events',
    }),
    'emergency-contactsID': one(emergency_contacts, {
      fields: [payload_locked_documents_rels['emergency-contactsID']],
      references: [emergency_contacts.id],
      relationName: 'emergency-contacts',
    }),
    addressesID: one(addresses, {
      fields: [payload_locked_documents_rels.addressesID],
      references: [addresses.id],
      relationName: 'addresses',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    vendorsID: one(vendors, {
      fields: [payload_locked_documents_rels.vendorsID],
      references: [vendors.id],
      relationName: 'vendors',
    }),
    merchantsID: one(merchants, {
      fields: [payload_locked_documents_rels.merchantsID],
      references: [merchants.id],
      relationName: 'merchants',
    }),
    'product-categoriesID': one(prod_categories, {
      fields: [payload_locked_documents_rels['product-categoriesID']],
      references: [prod_categories.id],
      relationName: 'product-categories',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_gender: typeof enum_users_gender
  enum_users_civil_status: typeof enum_users_civil_status
  enum_users_role: typeof enum_users_role
  enum_customers_current_level: typeof enum_customers_current_level
  enum_admins_admin_level: typeof enum_admins_admin_level
  enum_user_events_event_type: typeof enum_user_events_event_type
  enum_emergency_contacts_relationship: typeof enum_emergency_contacts_relationship
  enum_addresses_geocoding_accuracy: typeof enum_addresses_geocoding_accuracy
  enum_addresses_coordinate_source: typeof enum_addresses_coordinate_source
  enum_addresses_verification_method: typeof enum_addresses_verification_method
  enum_addresses_address_type: typeof enum_addresses_address_type
  enum_posts_status: typeof enum_posts_status
  enum__posts_v_version_status: typeof enum__posts_v_version_status
  enum_vendors_business_type: typeof enum_vendors_business_type
  enum_vendors_verification_status: typeof enum_vendors_verification_status
  enum_merchants_operational_status: typeof enum_merchants_operational_status
  enum_prod_categories_attributes_category_type: typeof enum_prod_categories_attributes_category_type
  enum_prod_categories_attributes_age_restriction: typeof enum_prod_categories_attributes_age_restriction
  enum_products_dietary_spice_level: typeof enum_products_dietary_spice_level
  enum_products_preparation_cooking_method: typeof enum_products_preparation_cooking_method
  users_sessions: typeof users_sessions
  users: typeof users
  customers: typeof customers
  admins: typeof admins
  user_events: typeof user_events
  emergency_contacts: typeof emergency_contacts
  addresses: typeof addresses
  media: typeof media
  posts_tags: typeof posts_tags
  posts: typeof posts
  _posts_v_version_tags: typeof _posts_v_version_tags
  _posts_v: typeof _posts_v
  vendors: typeof vendors
  merchants: typeof merchants
  prod_categories: typeof prod_categories
  products: typeof products
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_customers: typeof relations_customers
  relations_admins: typeof relations_admins
  relations_user_events: typeof relations_user_events
  relations_emergency_contacts: typeof relations_emergency_contacts
  relations_addresses: typeof relations_addresses
  relations_media: typeof relations_media
  relations_posts_tags: typeof relations_posts_tags
  relations_posts: typeof relations_posts
  relations__posts_v_version_tags: typeof relations__posts_v_version_tags
  relations__posts_v: typeof relations__posts_v
  relations_vendors: typeof relations_vendors
  relations_merchants: typeof relations_merchants
  relations_prod_categories: typeof relations_prod_categories
  relations_products: typeof relations_products
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
